# This is a test pipeline to demo terraform - app service creation
# branch is explicitly marked as none for it not to trigger any check-in.

# Pipelibe only builds the node app

trigger: none

schedules:
  - cron: "55 15 * * *"
    displayName: Daily 9:55 AM CT
    branches:
      include: 
      - main
    always: true
  - cron: "55 03 * * *"
    displayName: Daily 09:55 PM CT
    branches:
      include: 
      - main
    always: true

variables:
- group: TerraformVariableGroup
- name: subscription
  value: 'Visual Studio Subscription - 113136'
- name: location
  value: 'westus'
- name: artifactName
  value: 'drop'

stages:
- stage: Build
  displayName: 'Code Build'
  pool:
    name: "MyBuildAgents"
    demands: node.js
  jobs:
  - job: Build
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Terraforms to: $(build.artifactstagingdirectory)/Terraform'
      inputs:
        SourceFolder: Pipelines/Terraform
        TargetFolder: '$(build.artifactstagingdirectory)/Terraform'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'
      condition: succeededOrFailed()

- stage: SetupTerraformStorage
  displayName: 'Create storage for Terraform'
  dependsOn: Build
  pool:
    name: "MyBuildAgents"
    demands: node.js
  jobs:
  - job: Terraform
    steps:
    - task: AzureCLI@2
      displayName: 'Create storage for Terraform'
      inputs:
        azureSubscription: $(subscription) 
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #will create azure resource group for terraform workspace. terraform maintains its state here. 
          az group create --location $(location) --name $(terraformstoragerg) 
          az storage account create --name $(terraformstorageaccount) --resource-group $(terraformstoragerg) --location $(location) --sku standard_LRS 
          # Get storage account key
          ACCOUNT_KEY=$(az storage account keys list --resource-group $(terraformstoragerg)  --account-name $(terraformstorageaccount) --query '[0].value' -o tsv)
          az storage container create --name $(terraformcontainer) --account-name $(terraformstorageaccount) --account-key $ACCOUNT_KEY
        enabled: true
      continueOnError: true

- stage: SetupInfrastructure
  displayName: 'Setup Infrastructure with Terraform'

  dependsOn: SetupTerraformStorage
  pool:
    name: "MyBuildAgents"
    demands: node.js
  jobs:
  - job: Terraform
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        targetPath: '$(System.DefaultWorkingDirectory)'

    - task: replacetokens@3
      displayName: 'Replace tokens in terraform'
      inputs:
        rootDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        targetFiles: 'main.tf'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTransforms: false
        enableTelemetry: true

#    - task: AzurePowerShell@5
#      displayName: 'Get the storage key'
#      inputs:
#        azureSubscription: '$(subscription)'
#        ScriptType: 'InlineScript'
#        Inline: |
          #Using this script we will fetch storage key which is required in terraform file to authenticate backend storage account 
                    #$key = (Get-AzStorageAccountKey -ResourceGroupName $(terraformstoragerg) -AccountName $(terraformstorageaccount)).Value[0]
#                    $Key = (Get-AzStorageAccountKey -ResourceGroupName $(terraformstoragerg) -AccountName $(terraformstorageaccount)).Value[0]
          
#                    Write-Host "storage account key 1 = " $Key
                    
#                    Write-Host "##vso[task.setvariable variable=storagekey]$Key"
#        azurePowerShellVersion: latestVersion
#        pwsh: true
#        enabled: false

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '0.15.5'

#    - task: Bash@3
#      displayName: 'Debug Console'
#      inputs:
#        targetType: 'inline'
#        script: |
          # Write your commands here
#          echo 'Artifcat Path: $(System.DefaultWorkingDirectory)'

    - task: TerraformTaskV2@2
      displayName: 'Terraform : init'
      inputs:
        provider: 'azurerm'
        command: init
        commandOptions: '-reconfigure'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        backendServiceArm: '$(subscription)'
        backendAzureRmResourceGroupName: '$(terraformstoragerg)'
        backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
        backendAzureRmContainerName: $(terraformcontainer)
        backendAzureRmKey: 'terraform.tfstate'

#    - task: TerraformTaskV2@2
#      displayName: 'Terraform : plan'
#      inputs:
#        provider: 'azurerm'
#        command: 'plan'
#        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
#        environmentServiceNameAzureRM: '$(subscription)'

#    - task: TerraformTaskV2@2
#      displayName: 'Terraform : apply'
#      inputs:
#         provider: 'azurerm'
#         command: 'apply'
#         workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
#         commandOptions: '-auto-approve'
#         environmentServiceNameAzureRM: '$(subscription)'
#      continueOnError: true
    
    - task: TerraformTaskV2@2
      displayName: 'Terraform : destroy'
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: '$(subscription)'   
